INSERT INTO artist (name) VALUES
                             ('ABBA'),
                             ('2Cellos'),
                             ('Mišo Kovač'),
                             ('Beyonce'),
                             ('Spice Girls'),
                             ('Billy Jones & The Stars'),
                             ('Blackstreet'),
                             ('Oliver Dragojević'),
                             ('Magazin'),
                             ('Queen'),
                             ('Black Eyed Peace'),
                             ('Mozart'),
                             ('The Weeknd'),
                             ('Maroon 5'),
                             ('Thompson'),
                             ('Seka Alekić'),
                             ('Mozart'),
                             ('U2'),
                             ('Lady Gaga'),
                             ('Red Hot Chilly Pepers'),
                             ('Nirvana'),
                             ('Doja Cat'),
                             ('Beethoven'),
                             ('Gibonni'),
                             ('Dalmatino'),
                             ('Dino Merlin'),
                             ('Buč Kesidi'),
                             ('Dubioza Kolektiv'),
                             ('Magazin'),
                             ('Queen'),
                             ('Nirvana'),
                             ('BTS'),
                             ('Fat Boy Slim'),
                             ('Boris Brejcha'),
                             ('Skrillex'),
                             ('Morgan Wallen'),
                             ('Jennifer Lopez'),
                             ('Elvis Presley')