INSERT INTO subgenre (name, parent_genre_id) VALUES
                             ('Classic Rock',1),
                             ('Glam Rock',1),
                             ('Punk Rock',1),
                             ('Indie Rock',1),
                             ('Folk pop',2),
                             ('Chamber pop', 2),
                             ('Shiver pop', 2),
                             ('Hipster hip-hop',3),
                             ('Bounce', 3),
                             ('Cloud rap', 3),
                             ('Latin jazz',4),
                             ('Tejano', 4),
                             ('Reggaeton', 4),
                             ('House',5),
                             ('Techno', 5),
                             ('Dubstep', 5),
                             ('Disco',6),
                             ('Funk', 6),
                             ('Soul', 6),
                             ('Classic',7),
                             ('Canadian', 7),
                             ('Christian', 7),
                             ('Avant-Garde',8),
                             ('Chamber music', 8),
                             ('Choral',9),
                             ('Chamber pop', 9),
                             ('Shiver pop', 9),
                             ('Heavy metal',10),
                             ('Thrash metal', 10),
                             ('Black metal', 10),
                             ('Bop',11),
                             ('Swing', 11),
                             ('Funk', 11),
                             ('Country',12),
                             ('Urban', 12),
                             ('Harmonica', 12)
